### ISSUE TITLE
Almost completely broken on Dopamine 2.0.4, iOS 16.1.2 on iPhone XR

### ISSUE THREAD

**Issue by Yeet1000** [leminlimez/Lock-Master#4]
The tweak can only change the lock sound and that’s it

**Comment by leminlimez** [comment]
ios 16 skill issue, will not be fixed

**Comment by Yeet1000** [comment]
> ios 16 skill issue, will not be fixed

in that case #5 fixes some grammar issues and clarifies no iOS 16 support will exist
